# fly.toml app configuration file generated for bookkeeping-jammy on 2026-07-20T23:31:59-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bookkeeping-jammy'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile.fly'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
